.TH sip-sdist 1
.SH NAME
sip\-sdist - build an sdist for the sip project
.SH SYNOPSIS
.nf
sip\-sdist [options]
.fi
.SH DESCRIPTION
\fBsip\-sdist\fP creates an sdist (a source distribution) than be uploaded
to PyPI.
.SH OPTIONS
.TP
.B \-h, \-\-help
Display a help message.
.TP
.B \-V, \-\-version
Display the SIP version number.
.TP
.B \-\-name NAME
\fBNAME\fP is used instead of the PyPI project name in the
\fBpyproject.toml\fP file in the name of the sdist file.
